# -*- coding: utf-8 -*-
"""XTTS_VoiceCloningWorking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YIjUj2B9ad74rdRVdzQyXSA0SDQe164I
"""

# Clean environment
!pip uninstall -y TTS coqpit trainer librosa

# Install pinned dependencies
!pip install TTS==0.22.0
!pip install coqpit==0.0.17
!pip install trainer==0.0.36
!pip install librosa==0.10.0
!pip install soundfile

# Optional: GPU helpers
!pip install pysbd

!pip install coqui-tts

# Remove conflicting upstream package
!pip uninstall -y coqpit

# Install Coqui fork
!pip install coqpit-config

# Remove all conflicting packages
!pip uninstall -y TTS coqui-tts coqpit coqpit-config trainer

# Verify removal
!pip list | grep -E "TTS|coqpit|trainer"

import trainer
print(trainer.__version__)

import TTS, inspect
print(TTS.__file__)

!pip install coqui-tts
!pip install coqpit-config

import torch

print("CUDA available:", torch.cuda.is_available())
print("GPU name:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "None")

!pip list | grep -E "TTS|coqpit"

from TTS.api import TTS
tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2", gpu=True)

# generate speech by cloning a voice using default settings
tts.tts_to_file(text="To live is to give it your all. Anything less is just rehearsing for death.",
                file_path="output.wav",
                speaker_wav="/content/sample.ogg",
                language="en")





import torch
torch.cuda()



import sys
TTS_PATH = "/content/TTS/TTS"
# add libraries into environment
sys.path.append(TTS_PATH) # set this if TTS is not installed globally

import os
import string
import time
import argparse
import json

import numpy as np


import torch

from TTS.tts.utils.synthesis import synthesis
from TTS.tts.utils.text.symbols import make_symbols, phonemes, symbols
try:
  from TTS.utils.audio import AudioProcessor
except:
  from TTS.utils.audio import AudioProcessor


from TTS.tts.models import setup_model
from TTS.config import load_config